#!/usr/bin/env python
import sys, os

# Set the current working directory to the directory where this script is located
os.chdir(os.path.dirname(__file__))

# Determine MOOSE_DIR
MOOSE_DIR = os.getenv('MOOSE_DIR', os.path.abspath('moose'))
if not os.path.exists(os.path.join(MOOSE_DIR, 'framework', 'Makefile')):
    MOOSE_DIR = os.path.abspath(os.path.join('..', 'moose'))
if not os.path.exists(os.path.join(MOOSE_DIR, 'framework', 'Makefile')):
    msg = "Unable to locate MOOSE, there are three options:\n" \
          "   (1) Initialize the submodule with: 'git submodule update --init moose'\n" \
          "   (2) Clone MOOSE in a sister directory to MASTODON\n" \
          "   (3) Clone MOOSE in an arbitrary directory and set the MOOSE_DIR environment variable."
    raise EnvironmentError(msg)

# Add python directories
sys.path.append(os.path.join(MOOSE_DIR, 'python'))
sys.path.append(os.path.join(os.getcwd(), 'python'))
os.environ['PYTHONPATH'] = os.environ.get('PYTHONPATH', '') + \
                           ':' + os.path.join(MOOSE_DIR, 'python') + \
                           ':' + os.path.join(os.getcwd(), 'python')

# Import TestHarness
from TestHarness import TestHarness

# Run the tests!
sys.argv.insert(1, "--error")
TestHarness.buildAndRun(sys.argv, 'mastodon', MOOSE_DIR)
